### ISSUE TITLE
Invalid mesh, invalid collada file

### ISSUE THREAD

**Issue by Achllle** [PUT-UGV-Team/leo-marsyard#3]
I'm getting this when I launch gazebo after following the instructions.

```
[Err] [Visual.cc:2336] Visual::InsertMesh no submeshes, this is an invalid mesh
[Err] [Visual.cc:372] Ogre Error:OGRE EXCEPTION(2:InvalidParametersException): Header chunk didn't match either endian: Corrupted stream? in Serializer::determineEndianness at /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSerializer.cpp (line 89)
[Err] [Visual.cc:373] Unable to create a mesh from /home/ros/.gazebo/models/terrain/meshes/model4.obj
[Err] [ColladaLoader.cc:116] Invalid collada file. Must be version 1.4.0 or 1.4.1
```

**Comment by filesmuggler** [comment]
I have fixed version of collada file to 1.4.0 - it was caused by antenna model in the rover.
However we are unable reproduce your previous errors.
We also updated the structure of the repo. Try it and let me know if it works.

**Comment by Achllle** [comment]
Great!
I'm still not getting there.
```
Service call failed: transport error completing service call: unable to receive data from sender, check sender's logs for details

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
[ERROR] [1597829838.686398, 0.000000]: Spawn service failed. Exiting.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/user_camera/pose, deleting message. This warning is pr$nted only once.
(gdb) [leo/urdf_spawner-4] process has died [pid 1960, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -z 10.0 -$npause -urdf -model robot -param robot_description __name:=urdf_spawner __log:=/home/ros/.ros/log/8ad2be7a-e1ff-11ea-b546-024$ac110007/leo-urdf_spawner-4.log].
log file: /home/ros/.ros/log/8ad2be7a-e1ff-11ea-b546-0242ac110007/leo-urdf_spawner-4*.log
```

It's curious it drops into `gdb`. Not sure why..

**Comment by Achllle** [comment]
Aha. When I then in the vanilla gazebo click `insert` > `masyard_map`, it takes a few seconds and then crashes. Terminal says 'killed'. I think it soaks up too many resources and then gets killed by the kernel.

**Comment by Achllle** [comment]
Confirmed that that's the case as `roslaunch leo_gazebo empty_world.launch` works.
